/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import control.Treinador_ctr;
import model.Treinador;
/**
 *
 * @author gabri
 */
public class Cadastrotreinador extends javax.swing.JFrame {
    private static Cadastrotreinador instance;
    /**
     * Creates new form Cadastrotreinador
     */
    public Cadastrotreinador() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static Cadastrotreinador getInstance() {
        if (instance == null) {
            instance = new Cadastrotreinador();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlNome = new javax.swing.JLabel();
        JlIdade = new javax.swing.JLabel();
        JlCpf = new javax.swing.JLabel();
        JtNome = new javax.swing.JTextField();
        JtIdade = new javax.swing.JTextField();
        JtCpf = new javax.swing.JTextField();
        JbCadastrar = new javax.swing.JButton();
        JlFormacao = new javax.swing.JLabel();
        JtFormacao = new javax.swing.JTextField();
        JlTitulo = new javax.swing.JLabel();
        JlSenha = new javax.swing.JLabel();
        JtSenha = new javax.swing.JTextField();

        JlNome.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlNome.setText("Nome:");

        JlIdade.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlIdade.setText("Idade:");

        JlCpf.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlCpf.setText("CPF:");

        JtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNomeActionPerformed(evt);
            }
        });

        JbCadastrar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbCadastrar.setText("Cadastrar");
        JbCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastrarActionPerformed(evt);
            }
        });

        JlFormacao.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlFormacao.setText("Formação:");

        JlTitulo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        JlTitulo.setText("TempoTrail Cadastro");

        JlSenha.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        JlSenha.setText("Senha");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(JlTitulo)
                .addGap(81, 81, 81))
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlIdade)
                    .addComponent(JlCpf)
                    .addComponent(JlNome)
                    .addComponent(JlFormacao)
                    .addComponent(JlSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JbCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JtCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                    .addComponent(JtIdade)
                    .addComponent(JtNome)
                    .addComponent(JtFormacao)
                    .addComponent(JtSenha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(JlTitulo)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlNome)
                    .addComponent(JtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlIdade)
                    .addComponent(JtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlCpf)
                    .addComponent(JtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlFormacao)
                    .addComponent(JtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlSenha)
                    .addComponent(JtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(JbCadastrar)
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNomeActionPerformed

    private void JbCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastrarActionPerformed
        Treinador_ctr Tctr = new Treinador_ctr();
        Treinador t1 = new Treinador();
        
        t1.setNome(JtNome.getText());
        t1.setIdade(Integer.parseInt(JtIdade.getText()));
        t1.setSenha(JtSenha.getText());
        t1.setCpf(JtCpf.getText());
        t1.setFormacao(JtFormacao.getText());
        
        Tctr.cadastrarTreinador(t1);
        
        new LoginTreinador().setVisible(true);
    }//GEN-LAST:event_JbCadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastrotreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastrotreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastrotreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastrotreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastrotreinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCadastrar;
    private javax.swing.JLabel JlCpf;
    private javax.swing.JLabel JlFormacao;
    private javax.swing.JLabel JlIdade;
    private javax.swing.JLabel JlNome;
    private javax.swing.JLabel JlSenha;
    private javax.swing.JLabel JlTitulo;
    private javax.swing.JTextField JtCpf;
    private javax.swing.JTextField JtFormacao;
    private javax.swing.JTextField JtIdade;
    private javax.swing.JTextField JtNome;
    private javax.swing.JTextField JtSenha;
    // End of variables declaration//GEN-END:variables
}
