/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;
import model.Atleta;
import control.Atleta_ctr;
import javax.swing.JOptionPane;

/**
 *
 * @author gabri
 */
public class LoginAtleta extends javax.swing.JFrame {
    private static LoginAtleta instance;
    /**
     * Creates new form Login
     */
    public LoginAtleta() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static LoginAtleta getInstance() {
        if (instance == null) {
            instance = new LoginAtleta();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlNome = new javax.swing.JLabel();
        JlCPF = new javax.swing.JLabel();
        JtNomeAtleta = new javax.swing.JTextField();
        JtCpfAtleta = new javax.swing.JTextField();
        jlSenha = new javax.swing.JButton();
        JbCadastroAtleta = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        JtSenha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        JlNome.setText("Nome:");

        JlCPF.setText("CPF:");

        JtNomeAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNomeAtletaActionPerformed(evt);
            }
        });

        JtCpfAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCpfAtletaActionPerformed(evt);
            }
        });

        jlSenha.setText("LOGIN");
        jlSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jlSenhaActionPerformed(evt);
            }
        });

        JbCadastroAtleta.setText("CADASTRAR");
        JbCadastroAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastroAtletaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Login Atleta");

        jLabel2.setText("Senha");

        jLabel3.setText("Não tem conta ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlCPF)
                        .addGap(48, 48, 48)
                        .addComponent(JtCpfAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JlNome))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JtNomeAtleta, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                            .addComponent(JtSenha))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jlSenha)
                        .addGap(147, 147, 147))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(JbCadastroAtleta))
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlNome)
                    .addComponent(JtNomeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlCPF)
                    .addComponent(JtCpfAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jlSenha)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JbCadastroAtleta)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtNomeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNomeAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNomeAtletaActionPerformed

    private void JtCpfAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCpfAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtCpfAtletaActionPerformed

    private void JbCadastroAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastroAtletaActionPerformed
        new Cadastroatleta().setVisible(true);
    }//GEN-LAST:event_JbCadastroAtletaActionPerformed

    private void jlSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jlSenhaActionPerformed
        Atleta a1 = new Atleta();
        Atleta a_bd = new Atleta();
        Atleta_ctr actr = new Atleta_ctr();
        
        a1.setNome(JtNomeAtleta.getText());
        a1.setCpf(JtCpfAtleta.getText());
        a1.setSenha(JtSenha.getText());
        
        a_bd = actr.info_atleta_login(a1);
        
        if(a_bd != null){
            new Principal().setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(
                    null,
                    "usuario invalido!",
                    "login Atleta",
                    1
                );
        }
        
    }//GEN-LAST:event_jlSenhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAtleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCadastroAtleta;
    private javax.swing.JLabel JlCPF;
    private javax.swing.JLabel JlNome;
    private javax.swing.JTextField JtCpfAtleta;
    private javax.swing.JTextField JtNomeAtleta;
    private javax.swing.JTextField JtSenha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton jlSenha;
    // End of variables declaration//GEN-END:variables
}
