/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gabri
 */
public class LoginAtleta extends javax.swing.JFrame {
    private static LoginAtleta instance;
    /**
     * Creates new form Login
     */
    public LoginAtleta() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static LoginAtleta getInstance() {
        if (instance == null) {
            instance = new LoginAtleta();
        }
        return instance;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlNome = new javax.swing.JLabel();
        JlIdade = new javax.swing.JLabel();
        JlCPF = new javax.swing.JLabel();
        JtNomeAtleta = new javax.swing.JTextField();
        JtIdadeAtleta = new javax.swing.JTextField();
        JtCpfAtleta = new javax.swing.JTextField();
        JbLoginAtleta = new javax.swing.JButton();
        JbCadastroAtleta = new javax.swing.JButton();
        JlPeso = new javax.swing.JLabel();
        JlAltura = new javax.swing.JLabel();
        JlCategoria = new javax.swing.JLabel();
        JtPeso = new javax.swing.JTextField();
        JtAltura = new javax.swing.JTextField();
        Jtategoria = new javax.swing.JTextField();

        JlNome.setText("Nome:");

        JlIdade.setText("Idade:");

        JlCPF.setText("CPF:");

        JtNomeAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNomeAtletaActionPerformed(evt);
            }
        });

        JtIdadeAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtIdadeAtletaActionPerformed(evt);
            }
        });

        JtCpfAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCpfAtletaActionPerformed(evt);
            }
        });

        JbLoginAtleta.setText(" Login Atleta");
        JbLoginAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbLoginAtletaActionPerformed(evt);
            }
        });

        JbCadastroAtleta.setText("Cadastro");
        JbCadastroAtleta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastroAtletaActionPerformed(evt);
            }
        });

        JlPeso.setText("Peso:");

        JlAltura.setText("Altura Atleta:");

        JlCategoria.setText("Categoria:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(JbLoginAtleta)
                .addGap(71, 71, 71)
                .addComponent(JbCadastroAtleta)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JlCPF)
                        .addComponent(JlNome))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JlIdade)
                        .addGap(1, 1, 1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Jtategoria, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(JtNomeAtleta)
                        .addComponent(JtIdadeAtleta)
                        .addComponent(JtCpfAtleta)
                        .addComponent(JtPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(39, 39, 39)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JlPeso)
                        .addComponent(JlAltura)
                        .addComponent(JlCategoria))
                    .addGap(18, 18, 18)
                    .addComponent(JtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlNome)
                    .addComponent(JtNomeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlIdade)
                    .addComponent(JtIdadeAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlCPF)
                    .addComponent(JtCpfAtleta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JtPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(Jtategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbLoginAtleta)
                    .addComponent(JbCadastroAtleta))
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(114, 114, 114)
                    .addComponent(JlPeso)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(JtAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(JlAltura))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(JlCategoria)
                    .addContainerGap(120, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtNomeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNomeAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNomeAtletaActionPerformed

    private void JtIdadeAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtIdadeAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtIdadeAtletaActionPerformed

    private void JtCpfAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCpfAtletaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtCpfAtletaActionPerformed

    private void JbCadastroAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastroAtletaActionPerformed
        new Cadastroatleta().setVisible(true);
    }//GEN-LAST:event_JbCadastroAtletaActionPerformed

    private void JbLoginAtletaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbLoginAtletaActionPerformed
        new Principal().setVisible(true);
    }//GEN-LAST:event_JbLoginAtletaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginAtleta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginAtleta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCadastroAtleta;
    private javax.swing.JButton JbLoginAtleta;
    private javax.swing.JLabel JlAltura;
    private javax.swing.JLabel JlCPF;
    private javax.swing.JLabel JlCategoria;
    private javax.swing.JLabel JlIdade;
    private javax.swing.JLabel JlNome;
    private javax.swing.JLabel JlPeso;
    private javax.swing.JTextField JtAltura;
    private javax.swing.JTextField JtCpfAtleta;
    private javax.swing.JTextField JtIdadeAtleta;
    private javax.swing.JTextField JtNomeAtleta;
    private javax.swing.JTextField JtPeso;
    private javax.swing.JTextField Jtategoria;
    // End of variables declaration//GEN-END:variables
}
