/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author gabri
 */
public class LoginTreinador extends javax.swing.JFrame {
    private static LoginTreinador instance;
    /**
     * Creates new form LoginTreinador
     */
    public LoginTreinador() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static LoginTreinador getInstance() {
        if (instance == null){
            instance = new LoginTreinador();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlNome = new javax.swing.JLabel();
        JlIdade = new javax.swing.JLabel();
        JlCPF = new javax.swing.JLabel();
        JlFormacao = new javax.swing.JLabel();
        JtNomeTreinador = new javax.swing.JTextField();
        JtIdadeTreinador = new javax.swing.JTextField();
        JtCpfTreinador = new javax.swing.JTextField();
        JbLoginTreinador = new javax.swing.JButton();
        JbCadastroTreinador = new javax.swing.JButton();
        JtFormacao = new javax.swing.JTextField();

        JlNome.setText("Nome:");

        JlIdade.setText("Idade:");

        JlCPF.setText("CPF:");

        JlFormacao.setText("Formação:");

        JtNomeTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtNomeTreinadorActionPerformed(evt);
            }
        });

        JtIdadeTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtIdadeTreinadorActionPerformed(evt);
            }
        });

        JtCpfTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCpfTreinadorActionPerformed(evt);
            }
        });

        JbLoginTreinador.setText(" Login Treinador");
        JbLoginTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbLoginTreinadorActionPerformed(evt);
            }
        });

        JbCadastroTreinador.setText("Cadastro");
        JbCadastroTreinador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbCadastroTreinadorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlCPF)
                            .addComponent(JlNome))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(JlIdade)
                            .addGap(1, 1, 1)))
                    .addComponent(JlFormacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbLoginTreinador)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JbCadastroTreinador))
                    .addComponent(JtNomeTreinador, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(JtIdadeTreinador, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(JtCpfTreinador, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE)
                    .addComponent(JtFormacao))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlNome)
                    .addComponent(JtNomeTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlIdade)
                    .addComponent(JtIdadeTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlCPF)
                    .addComponent(JtCpfTreinador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtFormacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlFormacao))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbLoginTreinador)
                    .addComponent(JbCadastroTreinador))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JtNomeTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtNomeTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtNomeTreinadorActionPerformed

    private void JtIdadeTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtIdadeTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtIdadeTreinadorActionPerformed

    private void JtCpfTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCpfTreinadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtCpfTreinadorActionPerformed

    private void JbLoginTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbLoginTreinadorActionPerformed
        new Principal().setVisible(true);
    }//GEN-LAST:event_JbLoginTreinadorActionPerformed

    private void JbCadastroTreinadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbCadastroTreinadorActionPerformed
        new Cadastrotreinador().setVisible(true);
    }//GEN-LAST:event_JbCadastroTreinadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginTreinador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginTreinador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbCadastroTreinador;
    private javax.swing.JButton JbLoginTreinador;
    private javax.swing.JLabel JlCPF;
    private javax.swing.JLabel JlFormacao;
    private javax.swing.JLabel JlIdade;
    private javax.swing.JLabel JlNome;
    private javax.swing.JTextField JtCpfTreinador;
    private javax.swing.JTextField JtFormacao;
    private javax.swing.JTextField JtIdadeTreinador;
    private javax.swing.JTextField JtNomeTreinador;
    // End of variables declaration//GEN-END:variables
}
