
package view;

import model.Desempenho;
import control.Desempenho_ctr;
import control.Treino_ctr;
import model.Atleta;
import model.Treino;
/**
 *
 * @author gabri
 */
public class Treino_Tela extends javax.swing.JFrame {
    private static Treino_Tela instance;
    /**
     * Creates new form Treino
     */
    public Treino_Tela() {
        initComponents();
        setLocationRelativeTo(null);
    }
    
    public static Treino_Tela getInstance(){
        if (instance == null){
            instance = new Treino_Tela();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JlTitulo = new javax.swing.JLabel();
        JlDistancia = new javax.swing.JLabel();
        JlAlturacategoria = new javax.swing.JLabel();
        JlVelocidade = new javax.swing.JLabel();
        JtTempo = new javax.swing.JTextField();
        JtDistancia = new javax.swing.JTextField();
        JtAlturacategoria = new javax.swing.JTextField();
        JtVelocidade = new javax.swing.JTextField();
        JbAdicionar = new javax.swing.JButton();
        JbDesempenho = new javax.swing.JButton();
        JlTempo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        JtCpf = new javax.swing.JTextField();
        JbVerTreino = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JtpTreino = new javax.swing.JTextPane();

        JlTitulo.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JlTitulo.setText("Treino");

        JlDistancia.setText("Distancia:");

        JlAlturacategoria.setText("Altura de salto:");

        JlVelocidade.setText("Velocidade:");

        JbAdicionar.setText("Adicionar Resultado");
        JbAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbAdicionarActionPerformed(evt);
            }
        });

        JbDesempenho.setText("Desempenho");
        JbDesempenho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbDesempenhoActionPerformed(evt);
            }
        });

        JlTempo.setText("Tempo:");

        jLabel1.setText("cpf");

        JtCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JtCpfActionPerformed(evt);
            }
        });

        JbVerTreino.setText("Ver Treino");
        JbVerTreino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbVerTreinoActionPerformed(evt);
            }
        });

        jLabel2.setText("Adicione seu cpf para ver o treino e para salvar os dados de desempenho:");

        jScrollPane2.setViewportView(JtpTreino);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JlTempo)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(191, 191, 191)
                                .addComponent(JlTitulo))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(JlVelocidade)
                                    .addComponent(JlAlturacategoria)
                                    .addComponent(JlDistancia))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(JbAdicionar, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                                    .addComponent(JtAlturacategoria, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JtDistancia)
                                    .addComponent(JtTempo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JtVelocidade)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JbDesempenho, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JbVerTreino, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(JtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JtCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(JbVerTreino)
                        .addGap(26, 26, 26)
                        .addComponent(JbDesempenho))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtTempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JtDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlDistancia))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JtAlturacategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlAlturacategoria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JlVelocidade)
                    .addComponent(JtVelocidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(JbAdicionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbDesempenhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbDesempenhoActionPerformed
        new Desempenho_Tela().setVisible(true);
    }//GEN-LAST:event_JbDesempenhoActionPerformed

    private void JtCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JtCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JtCpfActionPerformed

    private void JbVerTreinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbVerTreinoActionPerformed
        Treino t1 = new Treino();
        Atleta a1 = new Atleta();
        Treino_ctr tctr = new Treino_ctr();
         a1.setCpf(JtCpf.getText());
         t1 = tctr.Exibir_teino(a1);
        JtpTreino.setText(t1.getExercicio());
    }//GEN-LAST:event_JbVerTreinoActionPerformed

    private void JbAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbAdicionarActionPerformed
        Desempenho d1 = new Desempenho();
        Desempenho_ctr Dctr = new Desempenho_ctr();
        Atleta a1 = new Atleta();
        
        d1.setTempo(Float.parseFloat(JtTempo.getText()));
        d1.setDistacia(Float.parseFloat(JtDistancia.getText()));
        d1.setAltuta_salto(Float.parseFloat(JtAlturacategoria.getText()));
        d1.setVelocidade(Float.parseFloat(JtVelocidade.getText()));
        a1.setCpf(JtCpf.getText());
        
        Dctr.add_desempenho_bd(d1, a1);
        
    }//GEN-LAST:event_JbAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Treino_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Treino_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Treino_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Treino_Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Treino_Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbAdicionar;
    private javax.swing.JButton JbDesempenho;
    private javax.swing.JButton JbVerTreino;
    private javax.swing.JLabel JlAlturacategoria;
    private javax.swing.JLabel JlDistancia;
    private javax.swing.JLabel JlTempo;
    private javax.swing.JLabel JlTitulo;
    private javax.swing.JLabel JlVelocidade;
    private javax.swing.JTextField JtAlturacategoria;
    private javax.swing.JTextField JtCpf;
    private javax.swing.JTextField JtDistancia;
    private javax.swing.JTextField JtTempo;
    private javax.swing.JTextField JtVelocidade;
    private javax.swing.JTextPane JtpTreino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
